# Generated by Django 5.1.3 on 2024-11-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift_store', '0002_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.IntegerField(default=0),
        ),
    ]
