# Generated by Django 5.1.3 on 2024-12-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift_store', '0006_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
