# Generated by Django 5.1.3 on 2024-12-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrift_store', '0007_product_cart_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
    ]
